package course.constant;

public enum ExceptionMessage {

    ACCOUNT_VIEW_ROLE_RESTRICTION,
    COURSE_ENROLL_ROLE_RESTRICTION,
    COURSE_EDIT_ROLE_RESTRICTION,
    COURSE_VIEW_ROLE_RESTRICTION,
    COURSE_OWNER_ERROR,
    ROLE_ERROR_REASON,
    COURSE_NOT_EXIST,
    COURSE_EDIT_RESTRICTION,
    SERVICE_NOT_FOUND_ERROR,
    WRONG_CREDENTIALS,
    ROLE_NOT_FOUND,
    REGISTER_ERROR
}
